"""Initial schema

Revision ID: 7f8e51df5bbd
Revises: 
Create Date: 2025-11-01 14:03:07.926251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f8e51df5bbd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'PROCESSED', 'FAILED', name='file_status_enum', create_constraint=True), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('uploader_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_assets_content_hash'), 'file_assets', ['content_hash'], unique=False)
    op.create_index(op.f('ix_file_assets_uploader_id'), 'file_assets', ['uploader_id'], unique=False)
    op.create_table('jobs',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('step', sa.String(length=64), nullable=True),
    sa.Column('progress', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_jobs_file_id'), 'jobs', ['file_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_no', sa.String(length=32), nullable=False),
    sa.Column('invoice_type', sa.Text(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('buyer_name', sa.Text(), nullable=True),
    sa.Column('buyer_tax_id', sa.Text(), nullable=True),
    sa.Column('seller_name', sa.Text(), nullable=True),
    sa.Column('seller_tax_id', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_tax', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.Enum('OK', 'WARN', 'ERROR', 'DUPLICATE', 'CONFLICT_DUPLICATE', name='invoice_status_enum', create_constraint=True), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('raw_ocr_text', sa.Text(), nullable=False),
    sa.Column('raw_ocr_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['file_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_no'), 'invoices', ['invoice_no'], unique=True)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_uploaded_by'), 'invoices', ['uploaded_by'], unique=False)
    op.create_table('invoice_anomalies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARN', 'ERROR', name='anomaly_severity_enum', create_constraint=True), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('field_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_anomalies_invoice_id'), 'invoice_anomalies', ['invoice_id'], unique=False)
    op.create_table('line_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=True),
    sa.Column('spec_model', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_items_invoice_id'), 'line_items', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_items_invoice_id'), table_name='line_items')
    op.drop_table('line_items')
    op.drop_index(op.f('ix_invoice_anomalies_invoice_id'), table_name='invoice_anomalies')
    op.drop_table('invoice_anomalies')
    op.drop_index(op.f('ix_invoices_uploaded_by'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_no'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_jobs_file_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_file_assets_uploader_id'), table_name='file_assets')
    op.drop_index(op.f('ix_file_assets_content_hash'), table_name='file_assets')
    op.drop_table('file_assets')
    # ### end Alembic commands ###
